ssu_make : ssu_make.c
	gcc -Wall -W ssu_make.c -o ssu_make
clean :
	rm ssu_make
hi :
	echo hello~
ping :
	echo pong
list : 
	ls -al *.c
backup :
	ls ssu_make.c
	cp ssu_make.c ssu_make_bak.c
everything: hi ping list backup

